services:
  # 数据库服务
  postgres:
    image: hub.kingschats.com/library/postgres:15
    environment:
      POSTGRES_DB: bidder_db
      POSTGRES_USER: bidder_user
      POSTGRES_PASSWORD: bidder_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bidder_network

  # Redis缓存服务
  redis:
    image: hub.kingschats.com/library/redis:7-alpine
    networks:
      - bidder_network

  # 后端API服务
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile

    depends_on:
      - postgres
      - redis
      # - chrome
    environment:
      # 数据库配置
      - DATABASE_URL=${DATABASE_URL:-postgresql://bidder_user:bidder_pass@postgres:5432/bidder_db}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      
      # AI服务配置
      - AI_PROVIDER=custom
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
      - OPENAI_VISION_MODEL=${OPENAI_VISION_MODEL:-gpt-4-vision-preview}
      
      # Azure OpenAI配置
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-02-01}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME:-}
      - AZURE_OPENAI_VISION_DEPLOYMENT_NAME=${AZURE_OPENAI_VISION_DEPLOYMENT_NAME:-}
      
      # 其他AI服务配置
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - CUSTOM_AI_API_KEY=sk-olXSWRMsoGdwlUBy4VNtwrXjDNEYfOy706FTmYF87apiSi8q
      - CUSTOM_AI_BASE_URL=http://192.168.11.4:3010/v1
      
      # 截图服务配置
      - SELENIUM_HUB_URL=${SELENIUM_HUB_URL:-http://chrome:4444/wd/hub}
      - ENABLE_SCREENSHOT=${ENABLE_SCREENSHOT:-false}
      - SCREENSHOT_TIMEOUT=${SCREENSHOT_TIMEOUT:-30}
      - SCREENSHOT_MAX_PAGES=${SCREENSHOT_MAX_PAGES:-20}
      
      # 文件上传配置
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-52428800}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES:-pdf,docx,doc,png,jpg,jpeg}
      - UPLOAD_PATH=${UPLOAD_PATH:-/app/uploads}
      - SCREENSHOT_PATH=${SCREENSHOT_PATH:-/app/screenshots}
      - GENERATED_DOCS_PATH=${GENERATED_DOCS_PATH:-/app/generated_docs}
      
      # 应用配置
      - APP_ENV=${APP_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      
      # 功能开关
      - ENABLE_AI=${ENABLE_AI:-true}
      - ENABLE_OCR=${ENABLE_OCR:-true}
      - ENABLE_DOCUMENT_GENERATION=${ENABLE_DOCUMENT_GENERATION:-true}
      
      # OCR配置
      - OCR_LANGUAGES=${OCR_LANGUAGES:-chi_sim+eng}
      - OCR_ENGINE=${OCR_ENGINE:-tesseract}
      
      # 文档生成配置
      - WORD_TEMPLATE_PATH=${WORD_TEMPLATE_PATH:-/app/templates}
      - DEFAULT_FONT=${DEFAULT_FONT:-Microsoft YaHei}
      - IMAGE_MAX_WIDTH=${IMAGE_MAX_WIDTH:-1654}
      - IMAGE_QUALITY=${IMAGE_QUALITY:-85}
      
      # 性能配置
      - WORKER_CONNECTIONS=${WORKER_CONNECTIONS:-1000}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-100}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-300}
      
      # 安全配置
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://frontend:3000}
      
      # 新增的MAX_UPLOAD_SIZE_MB
      - MAX_UPLOAD_SIZE_MB=${MAX_UPLOAD_SIZE_MB:-50}
      
      # 系统名称配置
      - APP_NAME=${APP_NAME:-投标苦}
      
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./screenshots:/app/screenshots
      - ./generated_docs:/app/generated_docs
      - ./templates:/app/templates
      - ./easyocr_models:/root/.EasyOCR  # EasyOCR模型持久化存储
    networks:
      - bidder_network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5555:3000"
    depends_on:
      - backend
    networks:
      - bidder_network
    environment:
      - VITE_MAX_UPLOAD_SIZE_MB=${MAX_UPLOAD_SIZE_MB:-50}
      - MAX_UPLOAD_SIZE_MB=${MAX_UPLOAD_SIZE_MB:-50}
      - VITE_APP_NAME=${APP_NAME:-投标苦}
      - VITE_PRODUCTION=${VITE_PRODUCTION:-false}
      - VITE_APP_FAVICON=${VITE_APP_FAVICON:-/favicon.ico}
      - VITE_APP_SUBTITLE=${VITE_APP_SUBTITLE:-法律人的投标自救工具}

  # Chrome浏览器服务用于网页截图
  # chrome:
  #   image: hub.kingschats.com/selenium/standalone-chrome:latest
  #   ports:
  #     - "4444:4444"
  #   networks:
  #     - bidder_network

volumes:
  postgres_data:

networks:
  bidder_network:
    driver: bridge 