services:
  # 数据库服务
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bidder_db
      POSTGRES_USER: bidder_user
      POSTGRES_PASSWORD: bidder_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bidder_network

  # Redis缓存服务
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - bidder_network

volumes:
  postgres_data:

networks:
  bidder_network:
    driver: bridge 