name: Make Images Public

on:
  workflow_run:
    workflows: ["Push Build and Push Images"]
    types:
      - completed

jobs:
  make-public:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: write

    steps:
    - name: Make Backend Image Public
      run: |
        echo "Making backend image public..."
        gh api \
          --method PATCH \
          /user/packages/container/${{ github.repository }}-backend/visibility \
          -f visibility=public

    - name: Make Frontend Image Public
      run: |
        echo "Making frontend image public..."
        gh api \
          --method PATCH \
          /user/packages/container/${{ github.repository }}-frontend/visibility \
          -f visibility=public

    - name: Generate summary
      run: |
        echo "## 🔓 Images Made Public Successfully!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The following images are now publicly accessible:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- \`ghcr.io/${{ github.repository }}/backend\`" >> $GITHUB_STEP_SUMMARY
        echo "- \`ghcr.io/${{ github.repository }}/frontend\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Anyone can now pull these images without authentication!" >> $GITHUB_STEP_SUMMARY 